# Generated by Django 6.0.3 on 2026-03-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('seats', models.IntegerField()),
                ('zone', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('bar', 'Bar')], max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved')], default='available', max_length=20)),
            ],
        ),
    ]
