# Generated by Django 6.0.3 on 2026-03-13 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shift',
            name='break_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('missed', 'Missed'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
    ]
